stages:
  - deploy

image: docker:20.10.16

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2 # specifies the storage driver for Docker
  DOCKER_TLS_CERTDIR: "/certs" # directory where TLS certificates are stored for secure communication with the Docker daemon
  DOCKER_TLS_VERIFY: 1 # enables TLS verification for secure Docker operations
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client" # path to the client TLS certificates
  CI_API_PATH: "api"
  CI_STREAMLIT_UI_PATH: "streamlit-ui"
  CI_GRADIO_UI_PATH: "gradio-ui"
  CI_PROJECT_DIR_API: "API"
  CI_PROJECT_DIR_STREAMLIT_UI: "Streamlit_UI"
  CI_PROJECT_DIR_GRADIO_UI: "gradio_docker"
  PROJECT_NAME: obesity
  API_VERSION: 0.1
  UI_VERSION: 0.2
  STREAMLIT_UI_VERSION: 0.2
  GRADIO_UI_VERSION: 0.3

services:
  - docker:20.10.16-dind # Docker-in-Docker (DinD) service image that allows running Docker commands inside a Docker container

before_script:
  - for try in {1..10}; do sleep 0.5; docker info && break ; done # attempts to connect to the Docker daemon up ensuring the Docker service is available before proceeding

deploy:
  stage: deploy
  image: bitnami/kubectl:latest # uses the latest Bitnami Kubectl image for interacting with Kubernetes
  script:
    - kubectl config use-context ${CI_PROJECT_PATH}:gitlab-agent #  account/project:<GitLab_agent_name> Replace <GitLab_agent_name> with the name of the agent in Managed Service for GitLab. 
    - kubectl rollout restart deployment api-obesity -n obesity

