services:
  api:
    build:
      context: ./API
    ports:
      - "8000:8000"
  
  ui_streamlit:
    build:
      context: ./Streamlit_UI
    ports:
      - "8501:8501"
    depends_on:
      - api

  ui_gradio:
    build:
      context: ./GradIO_UI
    ports:
      - "7860:7860"
    depends_on:
      - api